### ISSUE TITLE
Add malaria confirmation form to all profiles

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#1]
For all non-ANC and non-children U5 profiles, we need to add a button to the top right dropdown in a clients's profile to allow them to access to the Malaria Confirmation form. This will be the only possible entry point to the Malaria register.

Label for the button: `Malaria Confirmation`
Add this option in between Registration info and Remove this person.

![Screenshot_20190509-120514](https://user-images.githubusercontent.com/20777928/57524880-d5426200-7331-11e9-89e1-49f80a45de7d.png)

Tapping on this button opens the Malaria Confirmation form.

**Comment by whoisladleo** [comment]
@msschroeder what happens to the dialogue after the form is complete? Do we disable it or a person can be confirmed multiple times for malaria?

**Comment by whoisladleo** [comment]
@msschroeder do i also add it to the family profile?

**Comment by msschroeder** [comment]
@ladleo  
1. what happens to the dialogue after the form is complete? Do we disable it or a person can be confirmed multiple times for malaria?

If the person is added to the malaria register ([#17](https://github.com/OpenSRP/opensrp-client-chw-malaria/issues/17)), this form will no longer appear. 
If the person is not added to the malaria register, the form is closed and the form will still be available in the drop down as is noted in this issue.

2. Do i also add it to the family profile?
No, just the family member profiles

**Comment by msschroeder** [comment]
lgtm

**Comment by msschroeder** [comment]
QA 5 July Build:
- [x] Should not include "Follow-up Visit" in this menu. Should only appear in the drop down for those in the malaria register.

**Comment by msschroeder** [comment]
lgtm
