### ISSUE TITLE
Should we add a malaria icon for family register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#11]
Should we add an icon if a family member is part of the malaria register? 

@rowo Do we have an icon for a malaria client already?

**Comment by rowo** [comment]
@msschroeder Yes I think that would follow the current pattern established with the Liberia app. I do have an icon courtesy of the Reveal work: https://docs.google.com/presentation/d/1ckHp4pBFnGQPidDV55JPICutI6UfmQwiK5GAhQUA4gA/edit#slide=id.g51935574fe_4_89

**Comment by msschroeder** [comment]
@rowo Great! Where can we get the icon from?

**Comment by rowo** [comment]
@msschroeder the icons are now in the icon folder: https://drive.google.com/open?id=1XMVd5PJEZEanMs57tBgEWbhVJbRBNYG3

**Comment by msschroeder** [comment]
Closed with #37
