### ISSUE TITLE
Implement record malaria follow-up visit button row in malaria profile

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#20]
The follow-up visit appear according to the schedule (#6 ) 

On the malaria profile page, the visit buttons in the top row have various states:

<img width="254" alt="Screen_Shot_2019-05-09_at_10_05_37_PM" src="https://user-images.githubusercontent.com/20777928/57505359-b677a780-7300-11e9-954b-b82e94089f86.png">

- [x] This button will appear when `malaria_test_date` + 7 days
- [x] The blue record visit button opens the malaria follow-up visit form (#7 )

<img width="254" alt="Screen_Shot_2019-05-09_at_10_05_37_PM" src="https://user-images.githubusercontent.com/20777928/57505494-2e45d200-7301-11e9-8ccd-3fb457929e5d.png">

- [x] The above button in the overdue state (`malaria_test_date` + 10 days) turns red. 
- [x] Tapping on the red Record malaria follow-up button launches the malaria Follow-up Visit form

<img width="704" alt="49637613-ebf92b80-fa16-11e8-99f8-040248d4a0fb_png__706×140_" src="https://user-images.githubusercontent.com/20777928/57505680-fbe8a480-7301-11e9-9495-4c740286edb9.png">

~- [ ] When the follow-up visit is done, the follow-up visit button takes on a temporary state. Replace 'December visit done' with text in red, 'Follow-up visit done' similar to above. For the 24 hours after a follow-up visit is recorded, the user will have this status. After 24 hours, no button will appear for the follow-up visit.~
~- [ ] Tapping on the edit button launches the form that they submitted previously, where they can make edits.~

**Comment by whoisladleo** [comment]
Leaving this for now, waiting on #7 to be completed so i can move work on the rest of the tasks.

**Comment by msschroeder** [comment]
QA July 5 Build:
- [x] The button "Record malaria follow-up" appears when they are added to the registers rather than 7 days after the `malaria_test_date + 7 days`
- [x] The button "Record malaria follow-up" does not turn red after the `malaria_test_date + 10 days`

**Comment by manutarus** [comment]
@msschroeder the follow-up visit removes a record from the malaria register, this means that if we are removing the record immediately after completing the visit we are not able to edit the visit

**Comment by msschroeder** [comment]
@manutarus That is far. I have put a strike through the last few comments. We should not allow them to edit the form then.

**Comment by msschroeder** [comment]
lgtm
