### ISSUE TITLE
Add new icons to family register for malaria and implement logic for displaying it

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#37]
See design issue for context: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/16. We are introducing a new icon for the family register list: a mosquito icon to represent a client in the malaria register

![row-malaria](https://user-images.githubusercontent.com/20777928/59505905-741d2980-8eaf-11e9-8638-8e4da3e72391.png)

Below are the rules for when this icons appears and disappears from the family register list. 

- [x] First, the order of the icons in the family row in the register list should be in the order of the registers listed in the left navigation drawer of the app, i.e. ANC, PNC, Child, malaria.

**Rules:**

**NB:** start/end below refer to when the icon appears and no longer appears on the family record in the family register list.

- [ ] Mosquito icon for each record in the Malaria register
-- start: {malaria} = "1"
-- end: when a client is removed to a register (#23) : If {fever_still} = "No" in the follow-up visit form; if no follow-up visit has been done 15 days after {malaria_test_date} on a client in the malaria register; a malaria referral form to the health facility has been given.

**NB:** For all of the rules above, if the person's record is closed via the close family member or close U5 child form, the icon no longer appears as well. This is a rule across the board.

Related to #11

**Comment by msschroeder** [comment]
Icons can be found here: https://drive.google.com/file/d/1nk7SWX2rmy6eYguCKYEKprdehMc-9LPK/view?usp=sharing

**Comment by msschroeder** [comment]
@rowo UCC is saying that the icon row-malaria.png is too small for the register icon from my understanding. Is there another image that is larger ?

**Comment by rowo** [comment]
@msschroeder here is a new image that cuts out transparent image area and also is a big more vertical to help with spacing these icons

![row-malaria](https://user-images.githubusercontent.com/1584163/64530929-43953200-d2dc-11e9-9d49-dd69518e9242.png)

**Comment by msschroeder** [comment]
@ladleo Here, this should be sufficient.
@rowo Thanks

**Comment by msschroeder** [comment]
lgtm
