### ISSUE TITLE
Update and fix the malaria confirmation form

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#61]
- [x] Add the question `malaria_test_done` in row 10 -12 (highlighted in pink)
- [x] Update the relevance for `malaria_results` in row 13 (highlighted in pink) 
- [x] Fix the relevance to `{fever_malaria_chw} = Tested positive for malaria in the last 14 days in a health facility` in `date_hf_malaria_test`. 

Currently, this question only appears when  `{fever_malaria_chw} = Has fever `

- [x] Add the note in row 24 (highlighted in pink)

NOTE: We will have to add the referral component later.

- [x] Change `malaria_edu_chw` to select_mulitple as noted in the data dictionary

[Data Dictionary](https://docs.google.com/spreadsheets/d/1udEAH5_WR5BiRUhKOSIuurny4VxItQ0kjHw9zSaaKDk/edit?usp=sharing), CHW 1 - Malaria confirmation form

**Comment by whoisladleo** [comment]
There is no note in row 24

**Comment by msschroeder** [comment]
The note is in row 27

**Comment by msschroeder** [comment]
QA November 18:
- [ ] These questions are not seen in the APK

**Comment by msschroeder** [comment]
lgtm

**Comment by msschroeder** [comment]
closing to create one issue
