### ISSUE TITLE
Malaria Confirmation form workflow is not the same in Swahili as English

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#86]
### Issue
When you are filling the Malaria confirmation form, the workflow in English is correct, but not in Swahili. 

### Replicate
1. Switch to Kiswahili
2. Open a family on the All Families Register
3. Open a family profile (not ANC or U5 child)
4. Fill the Uthibitisho wa malaria form
5. Compare to the workflow in https://docs.google.com/spreadsheets/d/1udEAH5_WR5BiRUhKOSIuurny4VxItQ0kjHw9zSaaKDk/edit?usp=sharing

**Comment by paulinembabu** [comment]
@msschroeder The swahili form workflow needs to be amended

**Comment by allan-on** [comment]
- I checked the malaria confirmation (registration) forms and they differ in terms of workflow and form input types on some questions.

**Comment by msschroeder** [comment]
Looks great! Thanks @allan-allay

**Comment by Mstjamush** [comment]
Looks great
