### ISSUE TITLE
Swahili Malaria Confirmation form workflow incorrect

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#87]
Related to #86 (https://github.com/OpenSRP/opensrp-client-chw-malaria/issues/86)

### Issue
This is probably related to issue #86 (above), but with a Malaria Confirmation form is filled in Swahili, there is never a way a person can be added to the Malaria Register.

### To replicate
1. Switch to Kiswahili
2. Open a family on the All Families Register
3. Open a family profile (not ANC or U5 child)
4. Fill the Uthibitisho wa malaria form
5. Go to Malaria Register

**Comment by manutarus** [comment]
@msschroeder by this you mean the client is not being added to the malaria register after filling the form confirming them for malaria?

**Comment by msschroeder** [comment]
@manutarus Basically, when the swahili malaria confirmation form is filled on the CHW, the client is never added to the Malaria Register.

I suspect this is because the Swahili Malaria forms are not working well

**Comment by allan-on** [comment]
As identified in #86 and by @msschroeder the different workflows and form input fields were responsible for the client not being added on the Malaria register. 
This is fixed in now fixed by work done in #86

**Comment by Mstjamush** [comment]
Looks great
