### ISSUE TITLE
Malaria Diagnosis Form not available from the Health Facility Drop down

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#88]
- [ ] Add the Malaria Diagnosis form to the health facility profile drop down

**Comment by paulinembabu** [comment]
@msschroeder  Kindly share the Malaria Diagnosis Form that needs to be added.  Have Tried to look for the initial issue for this issue  to get the tagged form but I haven't seen it.

**Comment by msschroeder** [comment]
@paulinembabu All the HF forms are there - I just don't think they have been linked to the drop down.

The Malaria Diagnosis form has a name of malaria_follow_up_hf.json (English) and malaria_follow_up_hf_sw.json (Swahili)

**Comment by paulinembabu** [comment]
@msschroeder Have seen the file. Thank you

**Comment by msschroeder** [comment]
Looks great! Good job!
