### ISSUE TITLE
Design malaria medical history page

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#9]
For the medical history, I was thinking of including the following:

- date of a positive test for malaria

However, the question becomes what would this look like for those with multiple services - ANC, PNC, child U5? @rowo Do you have any thoughts on this?

**Comment by rowo** [comment]
@msschroeder I have to revisit this issue again looking at all of the history needs. Do you know which issue the discussion for the multiple histories is? I think it got closed but all of these directly related issues popped up without referencing it.

**Comment by msschroeder** [comment]
@rowo I think the issue you are looking for is this [one](https://github.com/OpenSRP/opensrp-client-chw/issues/250)

**Comment by msschroeder** [comment]
@cafootitt Do you have any thoughts or feedback on what you think we should display for malaria?

**Comment by rowo** [comment]
In https://github.com/OpenSRP/opensrp-client-chw/issues/250#issuecomment-479617795, @mberg suggested malaria isn't included in medical history at all. Should we revisit and decide on that point before discussing the specific items that would show up there?

**Comment by rowo** [comment]
@msschroeder so sounds like no malaria history — can we close this issue?

**Comment by msschroeder** [comment]
@rowo There will be no medical history for malaria. But it will pull all the data from other registers. I will create a new issue and close this issue.
